### ISSUE TITLE
Cloudflare Figuring Out How to ByPass This

### ISSUE THREAD

**Issue by IshanArya** [alessiop86/anti-antibot-cloudflare#1]
Won't it be really easy for Cloudflare to protect against your method if you make it open source? Not saying anything bad about your work. I mean, this source code is great! I'm just worried that Cloudflare might fix whatever way you bypass its system.

**Comment by alessiop86** [comment]
They still change their protection from time to time, I don't think my project can have any influence on that. 

I will have to update the project when that will happen
