### ISSUE TITLE
Get Images Binary

### ISSUE THREAD

**Issue by LEO318x** [alessiop86/anti-antibot-cloudflare#2]
Excellent tool bro but  I have a little problem :/ I can not get the images because returns as a string I tried to cast but it does not work. P.S.: Sorry for the bad english xD

Code:
AntiAntiBotCloudFlare getImage = new ApacheHttpAntiAntibotCloudFlareFactory().createInstance();

Object img = getImage.getUrl("http://domain.com/img/imagexyz.jpg"); (?)

**Comment by alessiop86** [comment]
Mmm I never tried getting anything different from an html document, now I am on holidays, when I come back I will try to test it with different content types.

Thanks for reporting the issue

**Comment by alessiop86** [comment]
@OWNED91 the site I was using to test the library has turned off the protection, so I am unable to test it. Could you provide a website with the protection active?

**Comment by LEO318x** [comment]
@alessiop86 here you go =)
Protected site with IUAM 
http://jkanime.io/assets/images/xlogo.png.pagespeed.ic.xusl0-49xz.png

SemiProtected No IUAM
http://animeflv.net/temas/v1/css/img/logo_naranja.png

**Comment by alessiop86** [comment]
I have released a prerelease, update in the pom/gradle the version to 1.1 and get images like this 

```
AntiAntiBotCloudFlare antiAntiBotCloudFlare = new OkHttpAntiAntibotCloudFlareFactory().createInstance(); //or ApacheHttpAntiAntibotCloudFlareFactory

byte[] bytes = antiAntiBotCloudFlare.getByteArrayFromUrl(imageUrl);

InputStream input = new ByteArrayInputStream(bytes);

OutputStream output = new FileOutputStream(localPath);

IOUtils.copy(input, output);
```

It should work, I will write better instructions and tidy up the code in the weekend or later.

**Comment by LEO318x** [comment]
The code works perfectly, great job, thanks for all. =)
